const Menu = [
  {
    id: 1,
    name: "maggi",
    image: "images/maggi.jpg",
    category: "breakfast",
    price: "22",
    description: "lorem ipus dolar sit amet consetetur adipisicing elit.",
  },

  {
    id: 2,
    name: "pizza",
    image: "images/pizza.jpg",
    category: "snacks",
    price: "299",
    description: "lorem ipus dolar sit amet consetetur adipisicing elit.",
  },
  {
    id: 3,
    name: "poha",
    image: "images/poha.jpg",
    category: "breakfast",
    price: "80",
    description: "lorem ipus dolar sit amet consetetur adipisicing elit.",
  },
  {
    id: 4,
    name: "samosa",
    image: "images/samosa.jpg",
    category: "breakfast",
    price: "12",
    description: "lorem ipus dolar sit amet consetetur adipisicing elit.",
  },
  {
    id: 5,
    name: "veg Thali",
    image: "images/veg-thali.jpg",
    category: "lunch",
    price: "299",
    description: "lorem ipus dolar sit amet consetetur adipisicing elit.",
  },
  {
    id: 6,
    name: "corns",
    image: "images/corns.jpg",
    category: "snacks",
    price: "90",
    description: "lorem ipus dolar sit amet consetetur adipisicing elit.",
  },
  {
    id: 7,
    name: "salid",
    image: "images/salid.jpg",
    category: "lunch",
    price: "199",
    description: "lorem ipus dolar sit amet consetetur adipisicing elit.",
  },
  {
    id: 8,
    name: "chhole bhature",
    image: "images/chhole bhature.jpg",
    category: "lunch",
    price: "150",
    description: "lorem ipus dolar sit amet consetetur adipisicing elit.",
  },

  {
    id: 9,
    name: "fried-rice",
    image: "images/fried-rice.jpg",
    category: "dinner",
    price: "120",
    description: "lorem ipus dolar sit amet consetetur adipisicing elit.",
  },
  {
    id: 10,
    name: "soup",
    image: "images/soup.jpg",
    category: "dinner",
    price: "200",
    description: "lorem ipus dolar sit amet consetetur adipisicing elit.",
  },
  {
    id: 11,
    name: "paneer sbji",
    image: "images/maggi.jpg",
    category: "dinner",
    price: "22",
    description: "lorem ipus dolar sit amet consetetur adipisicing elit.",
  },
  {
    id: 12,
    name: "Dal Makhni",
    image: "images/Dal Makhani.jpg",
    category: "dinner",
    price: "22",
    description: "lorem ipus dolar sit amet consetetur adipisicing elit.",
  },

  {
    id: 13,
    name: "Dal Makhni",
    image: "images/Dal Makhani.jpg",
    category: "lunch",
    price: "22",
    description: "lorem ipus dolar sit amet consetetur adipisicing elit.",
  },
];

export default Menu;
